# Generated by Django 4.0.4 on 2022-12-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=280)),
                ('image', models.CharField(max_length=300)),
                ('artist_name', models.CharField(max_length=280)),
                ('genre', models.CharField(max_length=280)),
                ('URI', models.CharField(max_length=280)),
            ],
        ),
    ]
